- README.md
I noticed that this was linking to production docs, which was unintentional.
> docs(github): change contributing link to use local repository file

- .github/ISSUE_TEMPLATE/feature_template.md
- .github/ISSUE_TEMPLATE/new_component_request.md
* Add hint to issue templates
* Add pull request template (copied from tds-core)
Yarn prepr output:
```
Changes:
- @tds/community-sample-pilter: 0.1.0 => 1.0.0 (private)
- @tds/shared-safe-rest: 1.0.0 => 2.0.0 (private)
```
☝️ probably from another impending pull request.
> chore(github): add component hint to new issue templates

- .all-contributorsrc
- .github/CONTRIBUTING.md
- README.md
- guide/README.md
- packages/Skeleton/package.json
* Change more URLs from telusdigital to telus
* Add Jesse to contributions table 🎉 
```
- @tds/community-skeleton: 0.1.0 => 0.2.0
- @tds/community-sample-pilter: 0.1.0 => 1.0.0 (private)
- @tds/shared-safe-rest: 0.1.0 => 1.0.0 (private)
```
How come skeleton wants to go to 0.2.0 🤔 
* Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
* make sure visual and accessibility tests pass
* paste the lerna version output
> docs(github): fix github URLs to use telus and not telusdigital

- packages/SideNavigation/SideNavigation.jsx
- packages/SideNavigation/SubMenu/SubMenu.jsx
- packages/SideNavigation/SubMenu/SubMenu.scss
- packages/SideNavigation/SubMenu/__tests__/__snapshots__/SubMenu.spec.jsx.snap
- packages/SideNavigation/__tests__/__snapshots__/SideNavigation.spec.jsx.snap
active submenu is not automatically open in site builder because of uglification
- [ x] New code is unit tested
- [ x] make sure visual and accessibility tests pass
- [x ] make sure code builds
lerna notice cli v3.8.0
lerna info versioning independent
lerna info Looking for changed packages since @tds/community-side-navigation@1.0.1
lerna WARN version Skipping working tree validation, proceed at your own risk
Changes:
- @tds/community-side-navigation: 1.0.1 => 1.0.2
> fix(community-side-navigation): active submenu auto open in site builder

- circle.yml
To facilitate with automated deployments, this displays the output of `prepr` in CircleCI logs when built on `master`.
> chore(other): log prepr in circle in all cases

- e2e/Dockerfile
- Update dockerfile to have parity with circleCI test image, that way e2e tests will run the same locally as well as in CI
> chore(e2e): update dockerfile to have parity with circleci

- scripts/commit-scope-lint.js
This PR fixes an issue where a scope error will occur if a contributor update takes place by adding an `excludedFiles` array.
> chore(scripts): prevent contributor updates from scope error

- circle.yml
This duplicates the change in tds-core that adds a rebase to the prepr-bot step on Circle CI.
> chore(other): add rebase to prepr-bot circle ci step

- packages/SideNavigation/SubMenu/SubMenu.jsx
- packages/SideNavigation/SubMenu/__tests__/__snapshots__/SubMenu.spec.jsx.snap
- packages/SideNavigation/__tests__/__snapshots__/SideNavigation.spec.jsx.snap
- packages/SideNavigation/package.json
Site Builder does not have a default font for buttons.  Need to explicitly state the default font for buttons
> Side navigation sub menu font

- package-lock.json
- packages/SideNavigation/SideNavigation.jsx
- packages/SideNavigation/SubMenu/SubMenu.jsx
- packages/SideNavigation/SubMenu/__tests__/__snapshots__/SubMenu.spec.jsx.snap
- packages/SideNavigation/__tests__/SideNavigation.spec.jsx
- packages/SideNavigation/__tests__/__snapshots__/SideNavigation.spec.jsx.snap
- packages/SideNavigation/package.json
https://github.com/telus/tds-community/issues/297
Fix 1: Fixes issue where opening a submenu can expand to outside of side navigation container
Feature 1: Collapsing the submenu will now fade out the text within the submenu
> fix(community-side-navigation): Side nav overflow fix

- packages/ToggleSwitch/ToggleSwitch.jsx
- packages/ToggleSwitch/__tests__/ToggleSwitch.spec.jsx
- packages/ToggleSwitch/__tests__/__snapshots__/ToggleSwitch.spec.jsx.snap
`ToggleSwitch` required `spinnerLabel`, yet `isLoading` prop is optional. `spinnerLabel` is only needed in cases where `isLoading` prop is passed.
Fixes issue #311
> fix(community-toggle-switch): makes spinnerLabel prop optional

- docs/setup/tds-core-globals.js
- packages/DatePicker/package.json
- packages/SideNavigation/package.json
- packages/_private/QuietButton/QuietButton.jsx
- packages/_private/QuietButton/QuietButton.md
- packages/_private/QuietButton/README.md
- packages/_private/QuietButton/__tests__/QuietButton.spec.jsx
- packages/_private/QuietButton/__tests__/__snapshots__/QuietButton.spec.jsx.snap
- packages/_private/QuietButton/index.cjs.js
- packages/_private/QuietButton/index.es.js
- packages/_private/QuietButton/package.json
- packages/_private/QuietButton/rollup.config.js
#New Quiet Button Component
See #361 
This pull request addresses [Jira Ticket DJR-2475](https://telusdigital.atlassian.net/browse/DJR-2475).
Quiet buttons are used sparingly and for an optional action. Mainly used in internal applications like My TELUS (web and app) or Casa; it only comes in one variant and size.
- _~~No~~_  **"Safe Rest"** properties are accepted (to allow `onClick` handler etc.)
- Child elements are accepted:
- [<InteractiveIcon>](https://tds.telus.com/components/index.html#/Icons?id=section-interactive-icons) is an appropriate child element, and can appear on the left or right of the text
- String text alone is an appropriate child element
- [<A11yContent>](https://tds.telus.com/components/index.html#/Content?id=a11ycontent) is an appropriate child element
Elements in …
> QuietButton Component

- packages/WaffleGrid/README.md
- packages/WaffleGrid/WaffleGrid.jsx
- packages/WaffleGrid/WaffleGrid.md
- packages/WaffleGrid/__tests__/WaffleGrid.spec.jsx
- packages/WaffleGrid/__tests__/__snapshots__/WaffleGrid.spec.jsx.snap
- packages/WaffleGrid/index.cjs.js
- packages/WaffleGrid/index.es.js
- packages/WaffleGrid/package.json
- packages/WaffleGrid/rollup.config.js
This is creating a new "Waffle" type like component where it adds `<HairlineDivider>` to separate the items in the component
`Desktop`
`Tablet`
`Mobile`
> feat(community-waffle-grid): add new waffle grid component

- packages/Modal/Modal.jsx
- packages/Modal/__tests__/Modal.spec.jsx
- Feat: `confirmCTAText` and `onConfirm` props are optional and backwards compatible
When there is no text provided to `confirmCTAText` , the confirm CTA should not appear
> feat(community-modal): make confirmCTAText and onConfirm props optional

- packages/RadioCard/README.md
- packages/RadioCard/RadioCard.jsx
- packages/RadioCard/RadioCard.md
- packages/RadioCard/__tests__/RadioCard.spec.jsx
- packages/RadioCard/__tests__/__snapshots__/RadioCard.spec.jsx.snap
- packages/RadioCard/index.cjs.js
- packages/RadioCard/index.es.js
- packages/RadioCard/package.json
- packages/RadioCard/rollup.config.js
- shared/utils/generateId/__tests__/generateId.spec.js
- shared/utils/generateId/generateId.js
- shared/utils/generateId/package.json
Similar to `Radio` buttons, `RadioCards` are used when there is a list of two or more options that are mutually exclusive and the user must select exactly one choice. `RadioCards` allow users to easily compare and see options with greater detail. Clicking anywhere on the card selects that option.
[Invision Designs](https://telus.invisionapp.com/d/main#/console/13362811/429359831/preview)
[Design in context](https://telus.invisionapp.com/d/main#/console/13362811/429359832/preview)
[Jira Ticket](https://telusdigital.atlassian.net/browse/DJR-2730)
> feat: RadioCard community component

- packages/QuietButton/QuietButton.jsx
- packages/QuietButton/__tests__/QuietButton.spec.jsx
- packages/QuietButton/__tests__/__snapshots__/QuietButton.spec.jsx.snap
- packages/QuietButton/package.json
Update to quietButton (private component). (Screen shot below is zoomed in & in focus/active state)
Addresses [**issue #362** ](https://github.com/telus/tds-community/issues/362).
Also **fixes a bug in the space function** (previously padding was being incorrectly applied to A11yContent and right text).
1. Change px units to rem units: **done.** 
2. Recommend Box instead of hard-coded padding: **done.**
- With regards to the vertical padding, the TDS component Box was not able to achieve this design as there is variable spacing on top and bottom of text (ie the text is not centre-aligned). This is mentioned in the designs and as such hard-coded vertical padding is required. See the [Invision design](https://telus.invisionapp.com/d/main#/console/13491097/419340834/preview).
3. Use …
> Quiet button (private component) update

- packages/InputGroup/style.js
See [HR-1605](https://telusdigital.atlassian.net/browse/HR-1605)
- Double border was appearing on safari browsers, this PR, explicitly removes the margin to align the text box with the left of the container
> fix(community-input-group): hr-1605 double border fix for safari

- packages/SkeletonProvider/SkeletonProvider.md
- packages/SkeletonProvider/__tests__/SkeletonProvider.spec.jsx
- packages/SkeletonProvider/__tests__/__snapshots__/SkeletonProvider.spec.jsx.snap
- packages/SkeletonProvider/package.json
- packages/SkeletonProvider/tds/Image.jsx
See #425 
This PR adds ability to create image skeleton with rounded corners.
> feat(community-skeleton-provider): add rounded corners to image skeleton

- packages/Modal/Modal.jsx
- packages/Modal/__tests__/__snapshots__/Modal.spec.jsx.snap
- packages/Modal/styles.jsx
See #403 
- Fix modal heading text overlap with close icon
##screenshots
> fix(community-modal): #403 fixed heading text overlap with close icon

- packages/Tabs/Tabs.jsx
- packages/Tabs/Tabs.md
- packages/Tabs/__tests__/Tabs.spec.jsx
- packages/Tabs/__tests__/__snapshots__/Tabs.spec.jsx.snap
- packages/Tabs/package.json
- packages/Tabs/styles.jsx
Adds support for optionally wrapping tab labels to multiple lines, for use in marketing contexts, following the [provided designs](https://telus.invisionapp.com/d/main#/console/18077659/426618923/inspect). The Boolean `wrapLabels` prop will limit the max-width of labels to 144px, wrapping as necessary.
While building this feature, the following issues were identified and fixed:
- **IE11 support** (7e7b56e120adf0496c0fa6bdca05348b1c59c570): the scrolling tabs feature would crash in IE11 due to lack of [NodeList.prototype.forEach](https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach) support
- **props/attrs warnings** (e530eecfb75a3fc6b9eb894a0b3ac27753fb0c9b): deconstruct `open`/`onOpen` props to remove from `rest`; fix issues with `tabIndex` attributes (case-sensitivity, …
> feat(community-tabs): add support for wrapping labels

- packages/Tabs/Tabs.jsx
- packages/Tabs/__tests__/__snapshots__/Tabs.spec.jsx.snap
- packages/Tabs/styles.jsx
only apply focus state through keyboard interaction
* Remove focus state on active tab if the tab is clicked on
* It should only apply focus state with keyboard interaction
> fix(community-tabs): fix focus state on active tab

- packages/Tabs/__tests__/__snapshots__/Tabs.spec.jsx.snap
- packages/Tabs/styles.jsx
This will fix issue where content is being cut off in tabs
Changes will remove `overflow: hidden`  so that content is not cut off. See example of issue in Site Builder below.
> fix(community-tabs): remove overlow-hidden

- packages/Modal/Modal.jsx
- packages/Modal/__tests__/Modal.spec.jsx
- packages/Modal/__tests__/__snapshots__/Modal.spec.jsx.snap
- packages/Modal/styles.jsx
Jira ticket [DJR-3335](https://telusdigital.atlassian.net/browse/DJR-3335)
**Current Issue:** 
Currently modal has a max-width limitation of 570px, so any flex-grid element inside modal having more than the default maxWidth causes the design broken
**Requirement** Modal width can expand up to 736px
**Fix**: 
Set the max-width of 736px
Set the min-width of 570px
Set the default width of 570px or by using `width` props provided to the Modal, that lies in the range of maxWidth-minWidth (i.e.: 570-736)
> feat(community-modal): update modal max-width

- packages/InputGroup/style.js
This is to fix the issue where the search button is cut off on mobile devices.
Changes will set the `min-width` of `InputGroup` to `200px` to ensure search button is not hidden on mobile devices.
> fix(community-input-group): change input group min width

- packages/SkeletonProvider/package.json
- packages/SkeletonProvider/tds/Text.jsx
This PR removes uuid and instead uses array indices as the `key` prop when mapping elements.  The main issue with using uuid is that it's bringing crypto into our browser bundles and this is very large (> 1MB in bundle builder). In the absence of a unique identifier, it's fine to use array indices as keys.
> feat(community-skeleton-provider): remove uuid to improve bundle size

- packages/SkeletonProvider/SkeletonProvider.jsx
- packages/SkeletonProvider/package.json
- packages/SkeletonProvider/withSkeleton.jsx
fix(community-skeleton-provider): allow id and additional props
See
https://telusdigital.atlassian.net/browse/NEO-1230
The recompose package is no longer maintained and has currently a critical-level vulnerability.  In this PR, we replace the use of recompose with React hooks. 
> fix(community-skeleton-provider): replaced recompose with react hooks

- docs/components/overrides/StyleGuide/StyleGuideRenderer.js
- TDS hasn't been supported in 2 years
- Applications need to use UDS to ensure efficient upgrade paths
- Update the warning message to provide information
> Update TDS inactive message
