telus/tds-community

- .github/ISSUE_TEMPLATES/defect_template.md
- .github/ISSUE_TEMPLATES/feature_template.md
> Docs: Added issue templates

- config/styleguide.config.js
None
Remove sample components from docs.
```
lerna info No updated packages to publish.
```
* Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
* make sure visual and accessibility tests pass
* paste the lerna version output
> docs(docs): remove sample components from styleguidist

- config/styleguide.config.js
None
* Add scoped package names to Styleguidist
* Group 'Progress' and 'Progress.Bar' component docs together
```
lerna info No updated packages to publish.
```
* Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
* make sure visual and accessibility tests pass
* paste the lerna version output
> chore(config): add scoped component imports to styleguidist

- docs/intro/welcome.md
* Add link to Contribution guide.
* Prettier made formatting changes in markdown
```
lerna info No updated packages to publish.
```
> docs(docs): add link to contribution guide

- .github/ISSUE_TEMPLATE/defect_template.md
* Feature 1
* Feature 2
* Patch 1
* Patch 2
```
Run `yarn prepr` locally and paste its output here, even when there are no changes
```
* Commits follow our [Developer Guide](https://github.com/telus/tds-community/blob/chore/template-hints/.github/CONTRIBUTING.md)
* make sure visual and accessibility tests pass
* paste the lerna version output
> updated reproduction steps example/description

- .github/PULL_REQUEST_TEMPLATE.md
- .travis.yml
- README.md
- scripts/travis/github-pr.js
Add TravisCI to run tests and `yarn prepr` in pull requests and branches. It is NOT meant to be a deployment method.
```
```
> ci(other): add travisci

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- yarn.lock
This adds some extra info to the contributing guide. Additionally, this updates the pull request template to account for TravisCI and TDSBot.
- make sure visual and accessibility tests pass
- paste the lerna version output
> docs(github): enhance contributing guide and pr template

- package.json
See https://github.com/telus/tds-core/pull/753
> chore(config): update husky hooks

- docs/intro/welcome.md
Added a short description and a link to [Community Heroes](https://tds.telus.com/community-heroes)
> Added a section about Community Heroes to the documentation

- .colophon.yml
> chore(other): add dpa members

- .github/ISSUE_TEMPLATE/defect_template.md
Make issue template better!
See https://github.com/telus/tds-core/pull/1155
> chore(github): update defect issue template

- package-lock.json
- package.json
> chore(deps): remove file-loader

- scripts/commit-scope-lint.js
> chore(scripts): allow for shared scope

- package.json
> fix(packages): fixing incorrect unit test watch script

- packages/ToggleSwitch/ToggleSwitch.md
Added description and design criteria, updated development criteria for concise and active language
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> docs(community-toggle-switch): Update usage criteria

- package.json
This bumps the repo package version to 2.1.0 after the Node 12 requirement update.
> chore(other): change package version

- config/styleguide.config.js
- docs/setup/tds-core-globals.js
- package-lock.json
- package.json
- packages/Pagination/package.json
- packages/SkeletonProvider/package.json
- packages/Tags/README.md
- packages/Tags/TagItem/TagItem.jsx
- packages/Tags/TagItem/TagItem.md
- packages/Tags/TagItem/__tests__/TagItem.spec.jsx
- packages/Tags/TagItem/__tests__/__snapshots__/TagItem.spec.jsx.snap
- packages/Tags/Tags.jsx
- packages/Tags/Tags.md
- packages/Tags/__tests__/Tags.spec.jsx
- packages/Tags/__tests__/__snapshots__/Tags.spec.jsx.snap
- packages/Tags/index.cjs.js
- packages/Tags/index.es.js
- packages/Tags/package.json
- packages/Tags/rollup.config.js
- packages/Tags/tagsText.js
- packages/ToggleSwitch/package.json
See #189 
- Add `Tags` component
- Waiting for TDS core `IconButton`
> Add Tags component

- packages/InputGroup/InputGroup.jsx
https://github.com/telus/tds-community/issues/347
- Fix id issue
> fix(community-input-group): update input id

- packages/CalloutParagraph/CalloutParagraph.jsx
- packages/CalloutParagraph/CalloutParagraph.md
- packages/CalloutParagraph/README.md
- packages/CalloutParagraph/__tests__/CalloutParagraph.spec.jsx
- packages/CalloutParagraph/__tests__/__snapshots__/CalloutParagraph.spec.jsx.snap
- packages/CalloutParagraph/index.cjs.js
- packages/CalloutParagraph/index.es.js
- packages/CalloutParagraph/package.json
- packages/CalloutParagraph/rollup.config.js
New component
It is compatible with tds-card with its spacing props.
> Rl 3862 call out paragraph

- circle.yml
> chore(other): fix bash error in update contributors

- packages/CalloutParagraph/__tests__/CalloutParagraph.spec.jsx
- packages/CalloutParagraph/__tests__/__snapshots__/CalloutParagraph.spec.jsx.snap
Fix prop type warnings for CalloutParagraph unit test
> test(community-callout-paragraph): fix proptype warnings in test

- openshift/openshift-template.yml
> chore(openshift): update cpu usage

- openshift/openshift-template.yml
This reverts commit 0a29f1f654bf1566d1079cf0298b0efab43c2ce2.
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> Revert "chore(openshift): update cpu usage"

- docs/components/overrides/StyleGuide/StyleGuideRenderer.js
- packages/Blockquote/package.json
- packages/CalloutParagraph/package.json
- packages/DatePicker/package.json
- packages/InputGroup/package.json
- packages/MiniExpandCollapse/Link/Link.jsx
- packages/MiniExpandCollapse/MiniExpandCollapse.jsx
- packages/MiniExpandCollapse/MiniExpandCollapse.md
- packages/MiniExpandCollapse/README.md
- packages/MiniExpandCollapse/__tests__/MiniExpandCollapse.spec.jsx
- packages/MiniExpandCollapse/__tests__/__snapshots__/MiniExpandCollapse.spec.jsx.snap
- packages/MiniExpandCollapse/createIconSizeProp.js
- packages/MiniExpandCollapse/index.cjs.js
- packages/MiniExpandCollapse/index.es.js
- packages/MiniExpandCollapse/package.json
- packages/MiniExpandCollapse/rollup.config.js
- packages/Modal/package.json
- packages/Pagination/package.json
- packages/PreviewCard/package.json
- packages/Progress/package.json
- packages/QuietButton/package.json
- packages/Ribbon/package.json
- packages/SideNavigation/package.json
- packages/Skeleton/package.json
- packages/SkeletonProvider/package.json
- packages/Tags/package.json
- packages/Testimonial/package.json
- packages/Toast/package.json
- packages/ToggleSwitch/package.json
- packages/WaffleGrid/package.json
- [word document with specs](https://docs.google.com/document/d/1Z7NnDa8VwND0fyN2vxhycl2IQlJxXuEBNjxjaTSRTTk/edit#)
- [designs](https://telus.invisionapp.com/d/main#/console/13362811/428786216/preview)
- a11yLabel functionality was manually tested on local machine
- desk check was done with @Christina-Lo
> miniExpandCollapse component

- package-lock.json
- packages/MiniExpandCollapse/package.json
- packages/PreviewCard/package.json
- packages/SideNavigation/package.json
- packages/Tags/package.json
- packages/Testimonial/package.json
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> Align @tds/util-prop-types

- circle.yml
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> chore(other): update contributor script

- packages/MiniExpandCollapse/MiniExpandCollapse.jsx
- packages/MiniExpandCollapse/__tests__/__snapshots__/MiniExpandCollapse.spec.jsx.snap
- packages/Tabs/package.json
Patch - removes unnecessary dependancy which should fix the pipeline
> Fix pipeline

- packages/MiniExpandCollapse/CHANGELOG.md
- packages/MiniExpandCollapse/package.json
- packages/Tabs/CHANGELOG.md
- packages/Tabs/package.json
This reverts commit 8348c23eefec59921911566fa3ae5a97089f4416.
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> revert(publish): update packages

- packages/Tabs/Tabs.jsx
- packages/Tabs/Tabs.md
- packages/Tabs/__tests__/__snapshots__/Tabs.spec.jsx.snap
- packages/Tabs/styles.jsx
Adds fixes to the Tabs beta component for accessibility and responsive design.
> Tabs fixes

- packages/CalloutParagraph/CalloutParagraph.jsx
- packages/CalloutParagraph/CalloutParagraph.md
- packages/CalloutParagraph/__tests__/__snapshots__/CalloutParagraph.spec.jsx.snap
See #411 
- Added `roundedCorners` prop to Callout Paragraph
> feat(community-callout-paragraph): add rounded corner option

- packages/CalloutParagraph/CalloutParagraph.jsx
See #411 
- reduce padding to match designs 
> fix(community-callout-paragraph): reduce padding to match designs

- packages/CalloutParagraph/CalloutParagraph.jsx
- packages/CalloutParagraph/package.json
update font size and line height for rounded corners
See #411 
- update font colour to Telus Purple
- reduce font size and add line height for rounded corners option
> fix(community-callout-paragraph): reduce font size and add line height

- packages/CalloutParagraph/CalloutParagraph.jsx
- packages/CalloutParagraph/CalloutParagraph.md
- packages/CalloutParagraph/__tests__/__snapshots__/CalloutParagraph.spec.jsx.snap
reduces size of padding and font
embargo link: https://services.trlcloud.com/prod/requestStatus/index.html?id=394455950
> feat(community-callout-paragraph): add compact prop

- packages/CalloutParagraph/CalloutParagraph.jsx
update mobile margin widths for rounded corners
> fix(community-callout-paragraph): fix margins for mobile width

- docs/setup/tds-core-globals.js
- package-lock.json
- package.json
- packages/Tabs/Tabs.jsx
- packages/Tabs/Tabs.md
- packages/Tabs/__tests__/Tabs.spec.jsx
- packages/Tabs/__tests__/__snapshots__/Tabs.spec.jsx.snap
- packages/Tabs/styles.jsx
- [HR-1595](https://telusdigital.atlassian.net/browse/HR-1595)
There was quite a bit of work to do with focus states in controlled more and stretch mode is no longer an issue, so I created this clean branch in favour of the spike branch.
Features:
- Controlled mode, open and onOpen used to control the component externally
- Use of hairline and dimple divider, and removed spacing as per https://telus.invisionapp.com/share/Z6V7MFS8Q7R#/screens
- Example docs/code and test
> feat(community-tabs): hr-1595 controlled mode

- packages/SkeletonProvider/package.json
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> fix(community-skeleton-provider): downgrade @tds/shared-styles to 1.5.2

- .colophon.yml
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> chore(other): update colophon

- packages/Tabs/Tabs.jsx
- packages/Tabs/__tests__/Tabs.spec.jsx
- packages/Tabs/__tests__/__snapshots__/Tabs.spec.jsx.snap
- packages/Tabs/styles.jsx
Allow tabbing by wrapping tabs in buttons
> Tabs a11y updates

- packages/Modal/Modal.jsx
- packages/Modal/__tests__/__snapshots__/Modal.spec.jsx.snap
See below issue for more details
#432
fix for modal bottom cta wrong padding top
- fix the top padding for the bottom action buttons
> Modal padding

- package-lock.json
- package.json
- packages/PreviewCard/PreviewCard.jsx
- packages/PreviewCard/PreviewCard.md
- packages/PreviewCard/__tests__/PreviewCard.spec.jsx
- packages/PreviewCard/__tests__/__snapshots__/PreviewCard.spec.jsx.snap
See [SSC-1829 ](https://telusdigital.atlassian.net/browse/SSC-1829)
- Support videos in Preview Card
> feat: [SSC-1829] support videos in PreviewCard

- docs/setup/tds-core-globals.js
> Add @tds/core-web-video to tds-core-globals

- packages/Tabs/Tabs.jsx
fix issue where left button doesn't show up when there are too few tabs
> fix(community-tabs): fix scroll issue

- docs/setup/tds-core-globals.js
- packages/CalloutParagraph/CalloutParagraph.jsx
- packages/CalloutParagraph/CalloutParagraph.md
- packages/CalloutParagraph/__tests__/CalloutParagraph.spec.jsx
- packages/CalloutParagraph/__tests__/__snapshots__/CalloutParagraph.spec.jsx.snap
Add optional icon before text
See #451 
- Add new 'icon' prop
- if this prop is supplied, it will display before the text
> feat(community-callout-paragraph): add icon support

- packages/CalloutParagraph/CalloutParagraph.jsx
- packages/CalloutParagraph/CalloutParagraph.md
- packages/CalloutParagraph/__tests__/CalloutParagraph.spec.jsx
- packages/CalloutParagraph/__tests__/__snapshots__/CalloutParagraph.spec.jsx.snap
add ability to specify text align
- add `textAlign` prop so that users can specify text align
> feat(community-callout-paragraph): add textAlign prop

- packages/CalloutParagraph/CalloutParagraph.jsx
Increase margin between icon and text
> fix(community-callout-paragraph): increase icon margin

- packages/OptimizeImage/package.json
align versions of core-responsive-image in master package and optimizeImage package (causing errors in pipeline)
> build(community-optimize-image): fix core-responsive-image version

- packages/MiniExpandCollapse/MiniExpandCollapse.jsx
- packages/MiniExpandCollapse/MiniExpandCollapse.md
- packages/MiniExpandCollapse/__tests__/MiniExpandCollapse.spec.jsx
- packages/MiniExpandCollapse/package-lock.json
created onclick event for mini-expand-collapse component
#495
See 
https://github.com/telus/tds-community/issues/495
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> feat(community-mini-expand-collapse): add mini-expand-collapse onclick

- packages/MiniExpandCollapse/MiniExpandCollapse.md
remove purple-block classname from last markdown example
#495
See 
#495 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> fix(community-mini-expand-collapse): fix markdown issue

- packages/OptimizeImage/OptimizeImage.jsx
- packages/OptimizeImage/OptimizeImage.md
- packages/OptimizeImage/__tests__/OptimizeImage.spec.jsx
- packages/OptimizeImage/__tests__/__snapshots__/OptimizeImage.spec.jsx.snap
Adds backwards compatibility for like to like use when replacing redux-contentful's responsive-image
> Optimize image compatibility

- Jenkinsfile
- openshift/install.sh
- openshift/openshift-template.yml
- openshift/run-build.sh
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> OSD4 Migration

- packages/MiniExpandCollapse/Link/Link.jsx
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> fix(community-mini-expand-collapse): accessible voice over on toggle

- packages/StoryCard/StoryCard.jsx
- packages/StoryCard/__tests__/__snapshots__/StoryCard.spec.jsx.snap
- packages/StoryCard/style.js
- Remove static heights from styling
- Remove extra div surrounding storycard
> fix(community-story-card): update height styling and remove div

- openshift/README.md
- openshift/install.sh
> fix: use shippy to get Vault secrets

- packages/DatePicker/DatePicker.jsx
See  #600 
Call Blur on input when not focusing
> fix(community-date-picker): remove blur on scroll end

- docs/components/overrides/StyleGuide/StyleGuideRenderer.js
This PR adds a TDS sunset warning for the Community component page.
> TDS sunset warning added for Community component page

- .github/workflows/tds-workflow.yml
See 
- Feature 1
- Feature 2
- Patch 1
- Patch 2
> update ci check
